# mlFlow Registry QA & Prod pipeline 

trigger:
- main

pool:
  name: Hosted Ubuntu 1604

steps:
- task: UsePythonVersion@0
  displayName: 'Use Python 3.7'
  inputs:
    versionSpec: 3.7
# databricks configure --token
# dbfs ls
- script: |
    pip install pytest requests setuptools wheel
    pip install -U databricks-cli
    echo $(DATABRICKS_HOST)
    databricks configure --token <<EOF
    $(DATABRICKS_HOST)
    $(DATABRICKS_TOKEN) 
    EOF
    echo -e "\nDatabricks workspace list:"
    databricks workspace ls
  displayName: 'Load Python Dependencies'

- checkout: self
  persistCredentials: true
  clean: true

- script: git checkout main
  displayName: 'Get Latest Branch'


- task: PythonScript@0
  inputs:
    scriptSource: 'filePath'
    scriptPath: '$(Build.Repository.LocalPath)/cicd-scripts/mlflow.py'
    arguments: ''
  displayName: 'Promote mlFlow Registry model to Production' 

- script: |
    echo $(response)
  displayName: 'Model Production Version'
